#!/usr/bin/env python3
"""
Live Onboard Console for Meter Data Monitoring

This script provides a live, continuously updating console view of the latest meter readings from the CSV files generated by the dashboard.

Usage:
    python3 live_console_monitor.py

It will auto-detect all CSVs in the csv_data/ directory and display the latest row for each, refreshing every few seconds.
"""
import os
import time
import csv
from pathlib import Path
from datetime import datetime

SCRIPT_DIR = Path(__file__).parent.absolute()
CSV_DIR = SCRIPT_DIR / "csv_data"
REFRESH_INTERVAL = 10  # seconds


def clear_screen():
    os.system('clear' if os.name == 'posix' else 'cls')


def get_csv_files():
    return sorted(CSV_DIR.glob("*.csv"))


def print_latest_readings():
    csv_files = get_csv_files()
    if not csv_files:
        print("No CSV files found in csv_data/ directory.")
        return
    for csv_file in csv_files:
        print(f"\n=== {csv_file.name} ===")
        try:
            with open(csv_file, 'r') as f:
                reader = list(csv.reader(f))
                if len(reader) < 2:
                    print("  No data yet.")
                else:
                    header = reader[0]
                    # Find the index for Device_ID or Device Name
                    device_id_idx = None
                    device_name_idx = None
                    for idx, col in enumerate(header):
                        if col.strip().lower() == 'device_id':
                            device_id_idx = idx
                        if col.strip().lower() == 'meter_name' or col.strip().lower() == 'device_name':
                            device_name_idx = idx
                    # Group by device (Device_ID or Device Name)
                    device_latest = {}
                    for row in reader[1:]:
                        key = None
                        if device_id_idx is not None:
                            key = row[device_id_idx]
                        elif device_name_idx is not None:
                            key = row[device_name_idx]
                        else:
                            key = 'Unknown'
                        device_latest[key] = row
                    print("  Time: ", datetime.now().strftime(
                        "%Y-%m-%d %H:%M:%S"))
                    for device, row in device_latest.items():
                        print(f"  --- Device: {device} ---")
                        for h, v in zip(header, row):
                            print(f"    {h}: {v}")
        except Exception as e:
            print(f"  Error reading {csv_file.name}: {e}")


def main():
    print("Live Onboard Console - Meter Data Monitor\nPress Ctrl+C to exit.\n")
    while True:
        clear_screen()
        print(
            f"Live Meter Data Monitor - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print_latest_readings()
        time.sleep(REFRESH_INTERVAL)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nExiting live monitor.")
