# Generated by Django 5.2.4 on 2025-08-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_name', models.CharField(max_length=100, unique=True)),
                ('pi_ip', models.GenericIPAddressField(unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('ssh_username', models.CharField(default='pi', help_text='SSH username for this Pi', max_length=50)),
                ('ssh_password', models.CharField(blank=True, help_text='SSH password (leave blank if using key)', max_length=100)),
                ('ssh_key_path', models.CharField(blank=True, help_text='Path to SSH private key file', max_length=500)),
                ('ssh_port', models.PositiveIntegerField(default=22, help_text='SSH port number')),
                ('config_path', models.CharField(default='/home/pi/meter_config', help_text='Path where config files are stored on Pi', max_length=200)),
                ('ssh_status', models.BooleanField(default=False, help_text='Last known SSH status (auto-updated)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raspberry Pi',
                'verbose_name_plural': 'Raspberry Pis',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_type', models.CharField(choices=[('DEVICE_CONFIG', 'Device Configuration'), ('SYSTEM_CONFIG', 'System Configuration'), ('BOTH', 'Both Configurations')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raspberry_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='device_manager.raspberrypi')),
            ],
            options={
                'verbose_name': 'Configuration Deployment',
                'verbose_name_plural': 'Configuration Deployments',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_mode', models.BooleanField(default=False, help_text='Set true to simulate readings')),
                ('reading_interval', models.PositiveIntegerField(default=30, help_text='Seconds between reading cycles')),
                ('inter_device_delay', models.FloatField(default=0.1, help_text='Delay (seconds) between device reads')),
                ('port', models.CharField(default='/dev/ttyUSB0', help_text='Serial port for Modbus', max_length=50)),
                ('enable_mqtt', models.BooleanField(default=False, help_text='Enable MQTT publishing')),
                ('enable_rtc', models.BooleanField(default=True, help_text='Enable RTC for offline time keeping')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raspberry_pi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_config', to='device_manager.raspberrypi')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='MeterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(max_length=100)),
                ('meter_address', models.PositiveIntegerField()),
                ('meter_model', models.CharField(help_text='Select from common models or enter a custom model name', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raspberry_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='device_manager.raspberrypi')),
            ],
            options={
                'verbose_name': 'Meter Device',
                'verbose_name_plural': 'Meter Devices',
                'unique_together': {('meter_address', 'raspberry_pi')},
            },
        ),
    ]
