# Generated by Django 5.2.5 on 2025-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
                ('meter_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('model', models.CharField(max_length=100)),
                ('watts_total', models.FloatField()),
                ('watts_r_ph', models.FloatField(blank=True, null=True)),
                ('watts_y_ph', models.FloatField(blank=True, null=True)),
                ('watts_b_ph', models.FloatField(blank=True, null=True)),
                ('pf_ave', models.FloatField(blank=True, null=True)),
                ('pf_r_ph', models.FloatField(blank=True, null=True)),
                ('pf_y_ph', models.FloatField(blank=True, null=True)),
                ('pf_b_ph', models.FloatField(blank=True, null=True)),
                ('vln_average', models.FloatField(blank=True, null=True)),
                ('v_r_ph', models.FloatField(blank=True, null=True)),
                ('v_y_ph', models.FloatField(blank=True, null=True)),
                ('v_b_ph', models.FloatField(blank=True, null=True)),
                ('a_average', models.FloatField(blank=True, null=True)),
                ('a_r_ph', models.FloatField(blank=True, null=True)),
                ('a_y_ph', models.FloatField(blank=True, null=True)),
                ('a_b_ph', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('wh_received', models.FloatField(blank=True, null=True)),
                ('load_hours_delivered', models.FloatField(blank=True, null=True)),
                ('no_of_interruption', models.IntegerField(blank=True, null=True)),
                ('on_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('v_r_harmonics', models.FloatField(blank=True, null=True)),
                ('v_y_harmonics', models.FloatField(blank=True, null=True)),
                ('v_b_harmonics', models.FloatField(blank=True, null=True)),
                ('a_r_harmonics', models.FloatField(blank=True, null=True)),
                ('a_y_harmonics', models.FloatField(blank=True, null=True)),
                ('a_b_harmonics', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
