# Generated by Django 5.2.4 on 2025-08-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_deviceconfig_configparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_name', models.CharField(max_length=100)),
                ('pi_ip', models.GenericIPAddressField(unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIMULATION_MODE', models.BooleanField(default=False)),
                ('READING_INTERVAL', models.IntegerField(default=30)),
                ('INTER_DEVICE_DELAY', models.FloatField(default=0.1)),
                ('PORT', models.CharField(default='/dev/ttyUSB0', max_length=100)),
                ('ENABLE_MQTT', models.BooleanField(default=False)),
                ('ENABLE_RTC', models.BooleanField(default=True)),
                ('LOG_LEVEL', models.CharField(default='INFO', max_length=10)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meters.device')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(max_length=100)),
                ('meter_address', models.IntegerField()),
                ('meter_model', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='meters.device')),
            ],
        ),
    ]
