# Generated by Django 5.2.4 on 2025-08-15 11:13

import django.db.models.deletion
import meters.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_device_config_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcmsPiSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_name', models.CharField(max_length=100, unique=True)),
                ('pi_ip', models.GenericIPAddressField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('ssh_username', models.CharField(max_length=50)),
                ('ssh_password', meters.encrypted_fields.EncryptedCharField(blank=True, help_text='Encrypted SSH password', max_length=1000)),
                ('ssh_key_path', meters.encrypted_fields.EncryptedCharField(blank=True, help_text='Encrypted SSH key file path', max_length=1000)),
                ('config_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DCMS Pi Setup',
                'verbose_name_plural': 'DCMS Pi Setups',
                'db_table': 'dcms_pi_setup',
            },
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='location',
        ),
        migrations.AlterModelTable(
            name='meterreading',
            table='meters_meterreading',
        ),
        migrations.CreateModel(
            name='EnvConfig',
            fields=[
                ('pi_setup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='env_config', serialize=False, to='meters.dcmspisetup')),
                ('simulation_mode', models.BooleanField(default=False)),
                ('reading_interval', models.IntegerField(default=30)),
                ('inter_device_delay', models.FloatField(default=0.1)),
                ('port', models.CharField(default='/dev/ttyUSB0', max_length=100)),
                ('enable_mqtt', models.BooleanField(default=False)),
                ('enable_rtc', models.BooleanField(default=True)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Environment Config',
                'verbose_name_plural': 'Environment Configs',
                'db_table': 'env_config',
            },
        ),
        migrations.AddField(
            model_name='meterreading',
            name='pi_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='meters.dcmspisetup'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['pi_setup', 'time'], name='meters_mete_pi_setu_ba2812_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['device_id', 'time'], name='meters_mete_device__aad9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['time'], name='meters_mete_time_f4fcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['meter_name'], name='meters_mete_meter_n_0aa6e7_idx'),
        ),
    ]
