# Generated by Django 5.2.4 on 2025-08-15 11:13

import meters.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_dcmspisetup_remove_meterreading_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmspisetup',
            name='ssh_key_path',
            field=meters.encrypted_fields.EncryptedCharField(blank=True, help_text='Encrypted SSH key file path', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dcmspisetup',
            name='ssh_password',
            field=meters.encrypted_fields.EncryptedCharField(blank=True, help_text='Encrypted SSH password', max_length=1000),
        ),
    ]
