#! /usr/bin/bash

#PostgreSQL Database Setup
#1. Install PostgreSQL

sudo apt update
sudo apt install postgresql postgresql-contrib

#2. Start and Enable PostgreSQL
sudo systemctl start postgresql
sudo systemctl enable postgresql

#3. Create Database and User
sudo -u postgres psql

# Inside the psql shell, run the following commands:
CREATE DATABASE mfmdb;
CREATE USER mfmuser WITH ENCRYPTED PASSWORD 'devi';
GRANT ALL PRIVILEGES ON DATABASE mfmdb TO mfmuser;
\q

#4. Configure PostgreSQL to Accept Remote Connections (Optional)
# Edit pg_hba.conf
sudo vi /etc/postgresql/*/main/postgresql.conf

#Set:
listen_addresses = '*'

# Edit pg_hba.conf: In pg_hba.conf, only allow trusted IPs, not 0.0.0.0/0.
sudo vi /etc/postgresql/*/main/pg_hba.conf

# Add the following line:
host    all             all             0.0.0.0/0               md5

# Restart PostgreSQL to apply changes
sudo systemctl restart postgresql

#5. Verify Connection
psql -U mfmuser -d mfmdb -h localhost -d mfmdb


#6. Create Tables and Schema using mfmdb.dump
pg_restore -U mfmuser -d mfmdb mfmdb.dump