# Generated by Django 5.2.5 on 2025-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='config_path',
            field=models.CharField(default='/home/pi/meter_config', help_text='Path where config files are stored on Pi', max_length=200),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='ssh_key_path',
            field=models.CharField(blank=True, help_text='Path to SSH private key file', max_length=500),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='ssh_password',
            field=models.CharField(blank=True, help_text='SSH password (leave blank if using key)', max_length=100),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22, help_text='SSH port number'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='ssh_username',
            field=models.CharField(default='pi', help_text='SSH username for this Pi', max_length=50),
        ),
    ]
