# Generated by Django 5.2.5 on 2025-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0002_raspberrypi_config_path_raspberrypi_ssh_key_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdevice',
            name='meter_model',
            field=models.CharField(help_text='Select from common models or enter a custom model name', max_length=100),
        ),
    ]
