# Generated by Django 5.2.4 on 2025-08-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0003_alter_meterdevice_meter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='ssh_key_configured',
            field=models.BooleanField(default=False, help_text='Whether SSH key has been set up for this Pi'),
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='ssh_setup_error',
            field=models.TextField(blank=True, help_text='Last error encountered during SSH setup'),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='ssh_password',
            field=models.CharField(blank=True, help_text='SSH password (temporary - used only for initial key setup)', max_length=100),
        ),
    ]
