# Generated by Django 5.2.4 on 2025-08-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0004_raspberrypi_ssh_key_configured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdevice',
            name='location',
        ),
    ]
