# Generated by Django 5.2.4 on 2025-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0005_remove_meterdevice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='enable_mqtt',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='enable_rtc',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='db_server_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Database Server IP', null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='enable_csv_write',
            field=models.BooleanField(default=False, help_text='Enable CSV writing'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='mqtt_broker_ip',
            field=models.GenericIPAddressField(blank=True, help_text='MQTT Broker IP', null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='server_api_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Server API IP', null=True),
        ),
    ]
