# Generated by Django 5.2.4 on 2025-10-05 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0006_remove_systemconfiguration_enable_mqtt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address (e.g. 00:1A:2B:3C:4D:5E)', max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g. 00:1A:2B:3C:4D:5E)', regex='^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$')], verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='db_server_ip',
            field=models.GenericIPAddressField(blank=True, help_text='DB SERVER IP', null=True, verbose_name='DB SERVER IP'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='mqtt_broker_ip',
            field=models.GenericIPAddressField(blank=True, help_text='MQTT BROKER IP', null=True, verbose_name='MQTT BROKER IP'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='server_api_ip',
            field=models.GenericIPAddressField(blank=True, help_text='SERVER API IP', null=True, verbose_name='SERVER API IP'),
        ),
    ]
