# Generated by Django 5.2.4 on 2025-10-05 09:21

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0007_raspberrypi_mac_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='ssh_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='SSH Password (temporary - used only for initial key setup)'),
        ),
    ]
