# Generated by Django 5.2.4 on 2025-10-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0008_alter_raspberrypi_ssh_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='config_path',
            field=models.CharField(blank=True, help_text='Path where config files are stored on Pi', max_length=200),
        ),
        migrations.CreateModel(
            name='OTADeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_dir', models.CharField(help_text='Directory on server to copy', max_length=500)),
                ('exclude_file', models.CharField(blank=True, help_text='Path to file listing patterns to exclude (like dont_scp)', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result_message', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raspberry_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_deployments', to='device_config.raspberrypi')),
            ],
        ),
    ]
