# Generated by Django 5.2.4 on 2025-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0009_alter_raspberrypi_config_path_otadeployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otadeployment',
            name='exclude_file',
            field=models.CharField(blank=True, default='/home/isha/deepak/MFM_offline_setup/legacy/scp/dont_scp', help_text='Path to file listing patterns to exclude (like dont_scp)', max_length=500),
        ),
    ]
