# Generated by Django 5.2.4 on 2026-01-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0017_set_reading_interval_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdevice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map display', max_digits=9, null=True),
        ),
    ]
